### ISSUE TITLE
Minor issue with jira provider

### ISSUE THREAD

**Issue by axrt** [rafi/vim-unite-issue#18]
Hey rafi!

There may be a minor bug:
autoload/issue/provider line195
```
" Get the amount of room for the ticket summary / labels
let ww = winwidth(0) - s_width - t_width - 37  
if ww < 0
       ww = 10
endif
```
I believe it should be `let ww = 10`, otherwise, it crashes.
Thanks!

**Comment by rafi** [comment]
Fixed. thank you!
